services:
  web:
    image: nginx:alpine
    container_name: opfw-web
    ports:
      - "${DOCKER_PORT:-80}:80"
    volumes:
      - panel_code:/var/www/html:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - panel
      - socket
    networks:
      - opfw-network

  panel:
    build:
      context: ./panel
    container_name: opfw-panel
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - DOCKER_MODE=true
    env_file:
      - .env
    volumes:
      - panel_code:/var/www/html
      - panel_storage:/var/www/html/storage
      - panel_envs:/var/www/html/envs
      - panel_discord_attachments:/var/www/html/public/_discord_attachments
      - panel_transcripts:/var/www/html/public/_transcripts
      - panel_uploads:/var/www/html/public/_uploads
      - ./.env:/var/www/html/.env:ro
      - ./panel/logs:/var/www/html/storage/logs
    networks:
      - opfw-network

  socket:
    build:
      context: ./socket
    container_name: opfw-socket
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - DOCKER_MODE=true
    env_file:
      - .env
    volumes:
     - panel_envs:/etc/opfw-config/envs:ro
     - ./.env:/etc/opfw-config/.env:ro
     - ./socket/_config.json:/usr/src/app/_config.json:ro
     - ./socket/logs:/usr/src/app/logs
    networks:
      - opfw-network

  influxdb:
    image: influxdb:2.7
    container_name: opfw-influxdb
    volumes:
      - ./influx/data:/var/lib/influxdb2
      - ./influx/config:/etc/influxdb2
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: root
      DOCKER_INFLUXDB_INIT_PASSWORD: password
      DOCKER_INFLUXDB_INIT_ORG: op-fw
      DOCKER_INFLUXDB_INIT_BUCKET: history
      DOCKER_INFLUXDB_INIT_RETENTION: 90d
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: hmqCfGSRS3UUjeQmzpTaH6Qhf8avPzDC
    networks:
      - opfw-network

volumes:
  panel_code:
  panel_storage:
  panel_envs:
  panel_discord_attachments:
  panel_transcripts:
  panel_uploads:

networks:
  opfw-network:
    driver: bridge